### ISSUE TITLE
Aligning Ship...

### ISSUE THREAD

**Issue by Eismoritz** [skai2/EDAutopilot#10]
Hey there,
I sadly got another issue after reinstalling the script.
First of all, sorry for spamming issues.
Now to my problem: Whenever I plan a route the script says "Aligning ship" and then it presses the keys w and e. That happens no matter what I do,
Have you got any solutions?

**Comment by Eismoritz** [comment]
Oh btw here are my settings:
![image](https://user-images.githubusercontent.com/41331432/49454593-bc171180-f7e5-11e8-87f0-156f27c438e3.png)
Not sure whether they are important or not

**Comment by skai2** [comment]
This project is back in development now, please try the new version of the AutoPilot if you're interested. There is no setup required and this issue should no longer exist.
