### ISSUE TITLE
Aborting after aligning ship

### ISSUE THREAD

**Issue by ak4ge** [skai2/EDAutopilot#11]
Hey,

I have an issue where after aligning the ship it just aborts. It briefly displays JUMP and throttles up the ship then instantly aborts and goes to 0% throttle.

GUI is default orange.

Any suggestions?

Thanks

**Comment by Eismoritz** [comment]
I've got the same problem

**Comment by Dwrety** [comment]
I have the same problem here with default orange UI:
Rounting -> Rounting complete-> Align->Alignment complete->throttle up->abort

**Comment by skai2** [comment]
This project is back in development now, please try the new version of the AutoPilot if you're interested. These issues should no longer exist.
