### ISSUE TITLE
I'm trying to run scripts, but I get an error

### ISSUE THREAD

**Issue by caleroni5** [skai2/EDAutopilot#12]
I am not strong in python, and I hope that you will tell what could be the matter:
D:\EDAutopilot-master\src>python GetNavPointOffset.py
Traceback (most recent call last):
  File "GetNavPointOffset.py", line 28, in <module>
    round(screenWidth *1/4)  : round(screenWidth * 2/4)]
TypeError: slice indices must be integers or None or have an __index__ method

D:\EDAutopilot-master\src>python GetDivertOffset.py
Traceback (most recent call last):
  File "GetDivertOffset.py", line 27, in <module>
    round(screenWidth *1/4)  : round(screenWidth * 2/4)]
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by skai2** [comment]
Please try the new version of the AutoPilot if you're interested. None of the above setup is required.
