### ISSUE TITLE
Get an error while launching

### ISSUE THREAD

**Issue by fousol** [skai2/EDAutopilot#14]
Getting an error after typing 'python autopilot.py'
`Traceback (most recent call last):
  File "autopilot.py", line 1, in <module>
    from dev_tray import tray
  File "C:\Users\fouso\Desktop\EDAutopilot-master\EDAutopilot\dev_tray.py", line 3, in <module>
    from dev_autopilot import autopilot, resource_path, get_bindings, clear_input
  File "C:\Users\fouso\Desktop\EDAutopilot-master\EDAutopilot\dev_autopilot.py", line 293, in <module>
    keys = get_bindings(PATH_KEYBINDINGS)
  File "C:\Users\fouso\Desktop\EDAutopilot-master\EDAutopilot\dev_autopilot.py", line 280, in get_bindings
    binding['key'] = SCANCODE[binding['pre_key']]
KeyError: 'DIK_▒'
`

**Comment by skai2** [comment]
Hey there,

You seem to missing necessary keybinds for the program to work.
You must go to your controls and make sure you have set primary keyboard
keys for all of the following:


   - In 'Flight Rotation':
      - Yaw Left
      - Yaw Right
      - Roll Left
      - Roll Right
      - Pitch Up
      - Pitch Down
   - In 'Flight Throttle':
      - Set Speed To 0%
      - Set Speed To 100%
   - In 'Flight Miscellaneous'
      - Toggle Frameshift Drive
   - In 'Mode Switches':
      - UI Focus
   - In 'Interface Mode':
      - UI Panel Up
      - UI Panel Down
      - UI Panel Left
      - UI Panel Right
      - UI Panel Select
      - UI Back
      - Next Panel Tab
   - In 'Headlook Mode':
      - Reset Headlook

**Comment by aradalienzzzz** [comment]
Also unbind the shift key to someting else, as that gave me an error even after setting up the keybinds

**Comment by skai2** [comment]
@aradalienzzzz that is odd, the shift key should work just fine. What did you bind shift to? If you could send me your autopilot.log it would also help.

**Comment by fousol** [comment]
I unbind all numpad keys and it succesfully launched. 
- Roll Left
- Roll Right
- Pitch Up
- Pitch Down
