### ISSUE TITLE
script automatically aborting for unknown cause

### ISSUE THREAD

**Issue by PyraFirestone** [skai2/EDAutopilot#2]
so i activate it, it say's "Routing" for about 10 seconds (ive already set a route in game) "route complete" "aborting" then for a few milliseconds say's "aligning ship" then nothing happens

**Comment by EnumC** [comment]
Check out this method:

```CheckRoute() {
  Advise("Routing", 0)
  if (HaveTarget() = 0) {
    if (GetNextSystem() = 0) {
        Advise("Route Complete",1)
        Abort()
    }
    else if (PlotNextBlock() = 1) {
      RouteIndex++
    }
    else {
      Advise("Plotting Failed", 1)
      ToggleGalaxyMap()
      Abort()
    }
  }
  return
}```
```
So if it shows 'aborting' right after it says `route complete`, I'd bet my 2c that either you didn't select the next system, or Data/ED-FastTravel.exe is not exporting the route correctly. In that case, you might want to check the Route.txt and LRRoute.txt to see if the route is saved correctly.

**Comment by skai2** [comment]
This project is back in active development now, please try the new version of the AutoPilot if you're interested. There is no setup required and this issue should no longer exist.
