### ISSUE TITLE
Failed to execute script autopilot

### ISSUE THREAD

**Issue by UnderbirdII** [skai2/EDAutopilot#24]
When starting the .exe it says "failed to execute script autopilot" and the log says the following:

`DEBUG:root:This is a DEBUG message. These information is usually used for troubleshooting
INFO:root:This is an INFO message. These information is usually used for conveying information
WARNING:root:some warning message. These information is usually used for warning
ERROR:root:some error message. These information is usually used for errors and should not happen
CRITICAL:root:some critical message. These information is usually used for critical error, and will usually result in an exception.
INFO:root:
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
---- AUTOPILOT DATA ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
INFO:root:RELEASE=v19.05.15-alpha-18
INFO:root:PATH_LOG_FILES=None
INFO:root:PATH_KEYBINDINGS=None
INFO:root:KEY_MOD_DELAY=0.01
INFO:root:KEY_DEFAULT_DELAY=0.2
INFO:root:KEY_REPEAT_DELAY=0.1
INFO:root:FUNCTION_DEFAULT_DELAY=0.5
INFO:root:SCREEN_WIDTH=1920
INFO:root:SCREEN_HEIGHT=1080
INFO:root:get_latest_log=C:\Users\username\Saved Games\Frontier Developments\Elite Dangerous\Journal.190608155143.01.log
DEBUG:root:ship={'time': 23393, 'status': 'in_supercruise', 'type': 'cobramkiii', 'location': 'Crucis Sector CL-Y c20', 'star_class': 'K', 'target': 'Kamuy', 'fuel_capacity': 16.0, 'fuel_level': 13.191662, 'fuel_percent': 82, 'is_scooping': False}
INFO:root:get_latest_keybinds=C:\Users\username\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\Custom.3.0.binds`

How can I fix this?
Thank you!

**Comment by Noodles4Pasta** [comment]
I also have this issue... Wondering if its related to win 10 1903?

**Comment by UnderbirdII** [comment]
Not an issue on new hardware.
