### ISSUE TITLE
How do I get it run on Linux

### ISSUE THREAD

**Issue by MemphisCornelius** [skai2/EDAutopilot#26]
When I am trying to execute the script I get following:

`
python3 autopilot.py 

(autopilot.py:5127): Gtk-WARNING **: 17:10:10.218: Locale not supported by C library.
        Using the fallback 'C' locale.
Traceback (most recent call last):
  File "autopilot.py", line 1, in <module>
    from dev_tray import tray
  File "/home/marvin/EDAutopilot/dev_tray.py", line 3, in <module>
    from dev_autopilot import autopilot, resource_path, get_bindings, clear_input, set_scanner, RELEASE
  File "/home/marvin/EDAutopilot/dev_autopilot.py", line 37, in <module>
    from PIL import ImageGrab
  File "/usr/lib/python3.7/site-packages/PIL/ImageGrab.py", line 22, in <module>
    raise ImportError("ImageGrab is macOS and Windows only")
ImportError: ImageGrab is macOS and Windows only
`

How do I get it run?

**Comment by skai2** [comment]
Hey there, this project has been on a hiatus for a while, so I'm sorry for the late reply. As you may have noticed from the log, this tool depends on software exclusive to windows. Currently I had no plans to make a linux compatible version but I intend to get back to developing this project soon, so I'll look into it and see what I can do.
