### ISSUE TITLE
Fails to find keybindings

### ISSUE THREAD

**Issue by joeythesaint** [skai2/EDAutopilot#38]
I started out looking at this thinking I was having the same issue as #37 but the debug log looks like it is actually failing to find my keybindings in the appropriate file.  I confirmed that file is present and readable and I've walked through the recommended steps in #37 (shutting down and restarting, ensuring I have a route plotted, etc.)

* [autopilot.log](https://github.com/skai2/EDAutopilot/files/4670875/autopilot.log)
* [Custom.3.0.binds.txt](https://github.com/skai2/EDAutopilot/files/4670880/Custom.3.0.binds.txt)

**Comment by TomW1605** [comment]
i haven't seen this before but it looks like it is finding but not reading the bindings file. can you answer a few questions.

is this the full log?
how long did it run?
what OS are you running?
are you running this from the exe or the python directly?

**Comment by joeythesaint** [comment]
Sure, thanks for the follow-up.

> is this the full log?

Yep.  If I run it multiple times I get the same thing multiple times, but that's it, nothing else in there.

> how long did it run?

About 30 seconds. It starts up, the cursor does the 'busy' animation, stops, starts again after a second, then ends with an error dialog with the message "Failed to execute script autopilot".

> what OS are you running?

Windows 10 Professional

> are you running this from the exe or the python directly?

I'm running it from the release exe

**Comment by TomW1605** [comment]
ok i apparently have seen this issue. i found an old log file on my computer that shows the exact same issue. this looks like it is the same issue as you are having: https://github.com/skai2/EDAutopilot/issues/29#issuecomment-576044721

if this does not work unfortunately i think the fix i ended up with was running the python directly. i don't remember if i needed to make changes to the coded or just run it as is but for now i suggest trying this and see what happens. unfortunately this is a relatively hard program to get running from source because it has a lot of dependencies. i recommend using an IDE that supports venv and automatic library installation (i use and like pycharm).

if you need help with this let me know

**Comment by joeythesaint** [comment]
Alright, so I installed pycharm and cloned the repo and after a bit of configuraiton stuff I was able to get the script to run.  It hasn't actually successfully jumped anywhere for me yet, but it doesn't crash and it's definitely functional.

It actually failed in a different way when I first started working with it, though, I had muplile crashes when it was parsing the file when it found I guess unexpected key combinations (`DIK_,` and `DIK_LESSTHAN` I remember specifically) so I wiped everything, went with an empty keyset and just mapped the critical ones and now it seems okay.

**Comment by TomW1605** [comment]
glad to hear you got it at least running. i suggest that you close this issue and open another one with your new issues.

**Comment by joeythesaint** [comment]
> glad to hear you got it at least running. i suggest that you close this issue and open another one with your new issues.

Sure thing.  when  I can better characterize them I'll open an issue for them, I quick test or restoring my previous keybindings didn't produce quite the same errors, so I'll try to narrow down the trigger and grab some logs when I do.

Thanks.

**Comment by TomW1605** [comment]
sorry there is one other thing i forgot to mention. i noticed that you are using a 1440p monitor. this might cause issues with the computer vision. i needed to up scale the template files for it to detect things on my 4k monitor. in my case it was just a 2x scale but i'm not sure what a 1440p monitor would need. if it would need anything at all. the main symptom of this is constantly pitching up (the fall back behaviour if it can't find the navball). if you see this try setting your display res to 1080 and the scale to 100% and if that works you might need to make some different templates.

if it helps here are my 4k ones: https://github.com/TomW1605/EDAutopilot/tree/master/templates

**Comment by joeythesaint** [comment]
Oh, yeah, so I did give that a try and it did get confused (90% pitching up with a little bit of roll left and right) on the native resolution, but when I switched down to 1080p resolution it seemed to work just fine.  Thanks!

**Comment by TomW1605** [comment]
glad to hear that worked. if you want to play at 1440p you can just scale the templates. there does not seem to be an issue with resolution. my 4k versions are not new images it is just the 1080p ones scaled up in MS paint and they work fine.
