### ISSUE TITLE
Need help setting up

### ISSUE THREAD

**Issue by HerrEurobeat** [skai2/EDAutopilot#4]
Hello,
where do i find the 'PitchModifierKey' and the 'YawModifierKey' in the ED settings?
Also some keybinds are not working. I set 'j' for jumping but when the autopilot displayes 'Jump' nothing happens. 
I also don't understand how to set up the ship parameters except of the roll360time and the yaw360time.

It would be very nice if you could make a youtube video on how to set up your autopilot because it is extremely confusing for me and some other people on how to measure everything, exspecially when your game is not in english.

**Comment by EnumC** [comment]
+1 on this issue. I'm going to assume the Pitch/Yaw Modifier keys are optional and are only used if we had those lateral thrusters binded to a modifier key in conjunction with a button. I changed them to an invalid value and it seems to be working fine.

**Comment by skai2** [comment]
This project is back in development now, please try the new version of the AutoPilot if you're interested. There is no setup required. Keybinds and everything else will be read automatically.
