### ISSUE TITLE
No module named src.directinput

### ISSUE THREAD

**Issue by AgentMoLnia** [skai2/EDAutopilot#40]
Hello. After comand "python autopilot.py" in command prompt - Import Error: No module named src.directinput.

What to do?

![image](https://user-images.githubusercontent.com/21228033/84602605-63700c80-ae91-11ea-9da9-10519afa9a56.png)

**Comment by AgentMoLnia** [comment]
![image](https://user-images.githubusercontent.com/21228033/84602702-f27d2480-ae91-11ea-85b3-5c0a6e0d80b6.png)

![image](https://user-images.githubusercontent.com/21228033/84602722-117bb680-ae92-11ea-9e1d-17578e74ad6e.png)

**Comment by TomW1605** [comment]
what version of python are you using?

**Comment by AgentMoLnia** [comment]
At first I installed the latest version of 3.8.3, but when "pip (or pip3) install -r requirements.txt" was an error about the wrong version (opencv-python = = 4.1.0.25)! Then I installed version 2.7 and the command "pip install -r requirements.txt" updated everything and downloaded it from the Internet.

**Comment by AgentMoLnia** [comment]
Which version is best used?

![image](https://user-images.githubusercontent.com/21228033/84631174-a19f1780-aef5-11ea-811b-515485ecef02.png)

**Comment by TomW1605** [comment]
try 3.6 and see if that works. if you get more errors from pip please post screenshots

**Comment by AgentMoLnia** [comment]
I installed 3.7.7, updated by requirements, reassigned the control keys in Elite, now the autopilot is running, the icon in the taskbar is present. But autopilot only increases the speed to 100% and everything :(

![image](https://user-images.githubusercontent.com/21228033/84749906-46d3f180-afc3-11ea-82ca-a759b9a0c085.png)


I adjusted game resolution: 1920х1080 Borderless
Ship UI color: Orange (default colour)
Ship UI brightness: Maximum

![image](https://user-images.githubusercontent.com/21228033/84749701-f9f01b00-afc2-11ea-9525-47acbd7ad66b.png)

What else should I check and configure?

**Comment by AgentMoLnia** [comment]
Yes, there are some difficulties with assigning keys when using this script :)

I have a question: in the control settings there are three places where the "home" key is used. Does this affect the operation of the autopilot?

![image](https://user-images.githubusercontent.com/21228033/84768577-257fff00-afdd-11ea-8fc5-f84cff9b0ed1.png)

**Comment by TomW1605** [comment]
i would advise changing those bindings to other keys. if that does not work please upload your logs.

**Comment by AgentMoLnia** [comment]
TomW1605, please share a "Custom.3.0.binds" file that does not conflict with the script.

**Comment by AgentMoLnia** [comment]
Autopilot stops on a step - DEBUG:root:align= find navpoint (speed 100%, no tilt, only forward, long time).

[autopilot.log](https://github.com/skai2/EDAutopilot/files/4789480/autopilot.log)

**Comment by TomW1605** [comment]
i think the issue might be that you have "CycleNextPanel" set to End. try binding this to a different key.
unfortunately my current bind set uses a gamepad as well but i will try and make one that works this evening (currently 7:30 am and i need to go to work so won't be for a while)

**Comment by AgentMoLnia** [comment]
I changed keys all day, but so far everything is unsuccessful.

[autopilot.log](https://github.com/skai2/EDAutopilot/files/4791153/autopilot.log)

**Comment by AgentMoLnia** [comment]
One from last error:

![image](https://user-images.githubusercontent.com/21228033/84921621-61928d00-b0cd-11ea-8f4a-d794cdad4e0a.png)

**Comment by AgentMoLnia** [comment]
In autopilot version from SpeedrunnerG55 (https://github.com/SpeedrunnerG55/EDAutopilot) i have next error:

![image](https://user-images.githubusercontent.com/21228033/84923043-5fc9c900-b0cf-11ea-98a8-c0ad82ddc110.png)


And I don't know what to do and who to ask advice: (

**Comment by TomW1605** [comment]
i think @SpeedrunnerG55 made changes to his repo that might break windows compatibility. you could try my fork (https://github.com/TomW1605/EDAutopilot) but there are a few changes. mostly that it uses page up and down instead of home and end because i didn't want to change my key binds.
not sure what the first error is but the error with @SpeedrunnerG55's repo looks like it is from his changed keyboard library.

**Comment by AgentMoLnia** [comment]
Thanks!

**Comment by TomW1605** [comment]
if you are using my repo i changed the binds to `page up` for start and `page down` for stop.

i also notice that you don't have a system targeted. the autopilot will turn itself off if there is no target

also if you edit an existing message that has already been read there is no notification so might be missed. i would advise not editing a message that is older than about 10-20 mins if it adds significant content

**Comment by AgentMoLnia** [comment]
Ok, i will try page up for start and page down for stop. I always choose the system to jump :)

**Comment by TomW1605** [comment]
in your last log it shows no target selected
> DEBUG:root:ship={'time': 103, 'status': 'in_space', 'type': 'cutter', 'location': 'Tewanta', 'star_class': None, **'target': None**, 'fuel_capacity': 64.0, 'fuel_level': 64.0, 'fuel_percent': 100, 'is_scooping': False}

but that is a side note as there would be a start and stop event in the logs and there is none so that is not the issue here

**Comment by SpeedrunnerG55** [comment]
> not sure what the first error is but the error with @SpeedrunnerG55's repo looks like it is from his changed keyboard library.

I did not include definitions for function keys for possible keyboard inputs py input defines the function keys as f1.. and not F1.  fix for that included in my latest push.

tho the way I handle screen input is also different because on my system I could not rely on using ratios of the screen because I have dual monitors and it used the combined screen space as one monitor. I'm not sure if that is a Linux issue or a dual monitor issue.

**Comment by TomW1605** [comment]
i think that is something that still wont work in windows. from what i can tell pynput can not handle direct input. i am working on a version of pyautogui that can use direct input but that is taking a while.

as for the screen issue i think that is a dual monitor on linux issue. i have dual monitors on windows and don't have an issue. although it might work to use a windows management library to get the extent of the ED window and then use ratios from there. this would be the most reliable.

also @SpeedrunnerG55 we should really have a chat about posable working together. we both seem to be going in similar directions with our forks and would probably benefit from working together.

**Comment by SpeedrunnerG55** [comment]
> also @SpeedrunnerG55 we should really have a chat about possibility working together. we both seem to be going in similar directions with our forks and would probably benefit from working together.

how should we communicate? I'm afraid we are getting off-topic here.

**Comment by AgentMoLnia** [comment]
I wish you a successful collaboration!

**Comment by AgentMoLnia** [comment]
The same error :(  :  step - DEBUG:root:align=find navpoint  -  

![image](https://user-images.githubusercontent.com/21228033/85067850-07bbc100-b1ba-11ea-9713-188d3e86cf0e.png)

[autopilot.log](https://github.com/skai2/EDAutopilot/files/4800992/autopilot.log)

**Comment by AgentMoLnia** [comment]
The same error in SpeedrunnerG55's autopilot version:

![image](https://user-images.githubusercontent.com/21228033/85068631-6e8daa00-b1bb-11ea-86de-3c73e81ff1ff.png)

**Comment by TomW1605** [comment]
ok it looks like it is not finding the template. i wonder if it is an issue with your username? could you try moving the folder to another drive? even a usb drive would do to test. also can you send a screenshot of the template folder?

**Comment by AgentMoLnia** [comment]
Yes. I moved the autopilot folder to C:\EDAutopilot and the ship began to move! Thanks! I will test further :)

**Comment by AgentMoLnia** [comment]
SpeedrunnerG55's autopilot version now has next error:

![image](https://user-images.githubusercontent.com/21228033/85108621-b858ad80-b218-11ea-8811-9e60f540b75f.png)

**Comment by TomW1605** [comment]
so what version worked? was it meant to do just one jump or did you stop it?

**Comment by AgentMoLnia** [comment]
Cutter is better for autopilot template function (i know inglish not very well):

![image](https://user-images.githubusercontent.com/21228033/85118218-b72f7c80-b228-11ea-89d5-7b6ba99bb0b6.png)

**Comment by TomW1605** [comment]
why is the compass white? do you have custom colours set up?

also if you are using my fork does it still have the previews showing?

**Comment by AgentMoLnia** [comment]
TomW1605, does autopilot have the function of guiding the ship to the station after the last jump along the route? Is it difficult to add it?

**Comment by AgentMoLnia** [comment]
most likely screenshot made during his blinking before the hyper-jump

**Comment by TomW1605** [comment]
not at the moment. there is currently no easy way to detect that there is a station targeted. i did start working on it but decided to make other improvements first as they were more pressing

**Comment by AgentMoLnia** [comment]
understandably, thank you, and in what direction do you work with an autopilot?

**Comment by TomW1605** [comment]
im currently working on redoing the input methods and minimising the number of required libraries. this is mainly for cross platform compatibility. i am planning to add a proper gui for settings including custom keybinds for start/stop

**Comment by SpeedrunnerG55** [comment]
> SpeedrunnerG55's autopilot version now has next error: 

I made a very silly mistake with handling the f keys in the dictionary. should be fixed now, however, once it does work it's most likely not going to work properly because the way I have it set up to work with my screens resolution and window setup.

**Comment by AgentMoLnia** [comment]
SpeedrunnerG55, what is your screens resolution and window setup? Can i try to change image resolutions in this folder? :

![image](https://user-images.githubusercontent.com/21228033/85161603-ae5e9b00-b268-11ea-9911-f836f91b7f5f.png)

**Comment by SpeedrunnerG55** [comment]
> SpeedrunnerG55, what is your screens resolution and window setup? Can i try to change image resolutions in this folder? :

last time I remember 
 I was useing 1600x900 screen resolution

**Comment by AgentMoLnia** [comment]
In window mode or boardlees ?

**Comment by SpeedrunnerG55** [comment]
borderless, the last time I remember. im having trouble launching it so I can't check right now to do much with it.

**Comment by TomW1605** [comment]
@AgentMoLnia have you gotten any version working? if so you should probably close the issue and open a new one for any new issues that come up.

also @SpeedrunnerG55 you might want to turn on issues on your fork so they can be kept separate from this repo.

**Comment by SpeedrunnerG55** [comment]
> also @SpeedrunnerG55 you might want to turn on issues on your fork so they can be kept separate from this repo.

Fixed, sry about that

**Comment by AgentMoLnia** [comment]
> @AgentMoLnia have you gotten any version working?

Your version is working now!

Can I ask other questions about autopilot and where better to do it?

**Comment by TomW1605** [comment]
great glad you got it working.

as for additional question. generally just make another issue if the question is distinctly different form the initial topic of the current issue.

**Comment by AgentMoLnia** [comment]
And the last question in this branch ))  @TomW1605  and @SpeedrunnerG55, what features (capabilities) do your autopilot versions have? And how can I enable these commands (features) ?

**Comment by TomW1605** [comment]
in my case there are no additional features. the only changes i have made are adding support for 4k monitors and some changes to improve the computer vision. i do have quite a few changes planned but they will take a while and will basically involve a complete rewrite. this mainly revolves around a proper GUI for settings like scan mode and keybinds but will also include a lot of under the hood changes.

**Comment by skai2** [comment]
This isn't quite the purpose of a git issue thread, but I've been watching this conversation form and can't help but share my own angle.

@SpeedrunnerG55 and @TomW1605, like @AgentMoLnia, I was wondering what sort of directions you had gone into in your respective forks, so I had a look and it seems to me there are very valuable enhancements to the program. Improvements, such as those stated in @TomW1605 future plans for instance, as well as those seen in @SpeedrunnerG55 repo, are not only great but essential to advance from an alpha stage and bring this program closer to a real Elite Autopilot (why on earth do we still not have one in 3306?)

When I decided to make this project public on GitHub I was hoping to garner support from other devs who also had a desire for an Autopilot written in an entirely external manner from the game, or even those who were curious to learn about about computer vision and automation. Over time though, despite there being a clear interest in the project, very few actually showed up to directly work on the code, and eventually, due to my own time constraints, work, etc, I ended up halting development as well.

There have been other attempts at this autopilot (either not published, of a primitive/heavily scripted nature, or involving hacking the games memory) but as far as I am aware none quite like this one. If you are interested, I would like to invite you both to become contributors here, so we can pool our resources, and resume progress in this project, faster and better than either of us alone could. Perhaps even set up a discord and reasonably regular talks, if you are so inclined. Eager to know what you think.

**Comment by AgentMoLnia** [comment]
I would love to help with advice and ideas)! I've been playing this game for a long time and I know it very well. But I am not a programmer, especially professional. I do not know the Python, although I own general concepts about programming ( . I played the Elite back in 1992. Then I tried programming in the programming language - Assembler, in Z80 (zx-spectrum)  :)

**Comment by skai2** [comment]
@AgentMoLnia Absolutely, you and any others with experience in Elite, programmers or not, would be welcome to join. We could setup such channels as suggestions, testing, etc. The more people helping and providing feedback the better.

**Comment by TheFatherMind** [comment]
I have been watching this project for a while. I would really love to see it advance forward.  I do not have the skill to work on it directly.  But I am here rooting for you and deeply appreciate all who contribute.  (:

**Comment by TheFatherMind** [comment]
And on that note.  I see that both @SpeedrunnerG55  and @TomW1605  have messed with the input/output and one of my issues is the ship getting lost and sometimes even flying back into the sun.  I wanted to test theirs.  But there are no releases for their forks.  And I am not very good with github and I do not have a development environment setup.  So how does one get to try their awesome code?

**Comment by TomW1605** [comment]
@TheFatherMind you should probably make an issue on the forks for that so we can help you more directly with specific issues you might have.

@skai2 i would be keen to contribute directly but i would suggest we might benefit from a method of more direct/real time communication such as discord so we can more easily unify our goals.

i have also made lots of changes along the same lines as SpeedrunnerG55 around restructuring the code and splitting off files. i have not been committing them (i know, i know) so have done them as one lump commit to a separate branch of my fork. do not try and use it it does not work yet. but feel free to have a look. but remember it is a mess. the main thing i was trying to do was redo the keyboard listeners so that the stop was more reliable. i was basically trying to redo how the threading worked to make it stoppable at any point in the autopilot. ideally every look would have an exit condition that could be triggered from outside so it would stop instantly.

**Comment by skai2** [comment]
Sounds like we can get started coordinating then! I am excited to resume active development of this project. I will get around to making an oficial disord then and will post the information on this repo. If you guys would like to send me your email that would also help. You can send it over to skai2mail@gmail.com if you would rather not post publicly here. @SpeedrunnerG55 the same for you if you are also on board friend!

@TomW1605 The structure changes you mention such as separating the files will be very welcome going forward seeing as we will have more active developers. So far I have gone with jupyter notebook based development (are you familiar with ipynb notebooks?), but I belive separating functions / organizing into proper program structure is the way to go moving forward. As for the computer vision side, I'll be happy to share what I know and I'm sure you'll get the hang of it quickly as you said. There is much to be improved in the cv as well.

**Comment by mrfisse** [comment]
@TomW1605 Hi, tried your version of this and having issues getting it to work. Running 1920x1080, borderless. Ship just does looptiloops and never activates the FSD. Getting this error message.

`Exception in thread EDAutopilot:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Python38-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\john\EDAutopilot\dev_autopilot.py", line 1008, in autopilot
    align()
  File "C:\Users\john\EDAutopilot\dev_autopilot.py", line 800, in align
    off = get_navpoint_offset()
  File "C:\Users\john\EDAutopilot\dev_autopilot.py", line 631, in get_navpoint_offset
    filtered = filter_blue(compass_image)
  File "C:\Users\john\EDAutopilot\dev_autopilot.py", line 557, in filter_blue
    hsv = cv2.cvtColor(hsv, cv2.COLOR_BGR2HSV)
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'`

**Comment by TomW1605** [comment]
@skai2 i think a discord would be great. as to the redesign you probably noticed that both @SpeedrunnerG55 and i got rid of the jupyter notebook very quickly. i think while it is a good system for a small file it is not a replacement for splitting a massive file into smaller, more manageable files. i am not familiar with ipynb notebooks and had not used jupyter before this project, however, about a week after i removed it i needed to learn how to use it to help my sister with a python unit for uni but i'm not really comfortable with it and dont like how much it adds to the raw file.

@mrfisse i have replied to you in the issue you opened on my fork. we should try and keep different issues separate.
