### ISSUE TITLE
Mostly Great! But questions..

### ISSUE THREAD

**Issue by DarkTearGames** [skai2/EDAutopilot#50]
Hey there! works great for a few minutes, between 10-30 minutes. Then the alignment to target becomes off center over time, to a point that jump fails more than 3 times which errors out the program. Never had any issues with it running into stars (unless I have a cheat engine trainer running, somehow that messes with the program).

this is great for as you say not to leave unattended, but wondering if you've abandoned this project. is there plans to make this fully autopilot? I'm willing to donate if so. 

Also, I'm about to dive into learning python and Computer Vision, I only know java, and C# through unity. is there any udemy courses I can take to learn how to recreate or even contribute to something like this?

**Comment by TomW1605** [comment]
what part of the alignment becomes off center? is it during the final target alignment?

the best way to contribute at the moment is to join the discord server linked in the readme (also the best way to debug issues you might be having)

**Comment by DarkTearGames** [comment]
Thanks for the response! Yes it's during the final alignment. It tries to jump before the target circle is fully centered.

Thanks I'll check that out!
