### ISSUE TITLE
Not enought sensitivity of red color

### ISSUE THREAD

**Issue by TeoVenturini** [skai2/EDAutopilot#6]
Itere some big gas stars that got about 70-100 red. I guess 60 points of red for alert is good as i tested.
P.S. Make a small video guide how to startup the program. Everyone has got tons of problems with installing. Short 5min video will make everyone more happy:)

**Comment by EnumC** [comment]
I have set the default red to 240 since that seems to be the safest trigger value for ~90% of the stars. The main thing is that if any red warnings or anything else that's not in the low red spectrum shows up, the whole thing aborts. How much luck are you having with setting it to 60?

**Comment by TeoVenturini** [comment]
As i understand, color is checking only in center pixel. In exact center pixel there is no warnings.

**Comment by EnumC** [comment]
@TeoVenturini No, I was originally planning to do that, but I opted to use a library someone posted on AHK's forum which averages a small area. It's currently set to 20x20 I believe.

**Comment by skai2** [comment]
This project is back in active development, please try the new version of the AutoPilot if you're interested. There is no setup required and this issue should no longer exist as everything has been overhauled.
