### ISSUE TITLE
Routing complete...Aborting

### ISSUE THREAD

**Issue by cryptichush** [skai2/EDAutopilot#7]
g´day

i have already set a route in game, select the next system, then i activate Autopilot, it say's "Routing" then a message popped up: Aborting

i checked \Data\GetNavPointOffset\GetNavPointOffset.exe, its generate two files: NavPoint.txt and RouteIndex.txt 

the content insite those files is always -1 and 1

how can i see if the route is saved correctly?

**Comment by EnumC** [comment]
I'm not the original author for this program, but I'd say check out #2 and see if that's the issue you are having. Does it say "Route Complete" or "Routing Failed"? It might show up very briefly for only a second, but there should be a message prior to being overwritten by the "Aborting..." message.

**Comment by Eismoritz** [comment]
Hey, did you find the answer? I got the same problem

**Comment by skai2** [comment]
Forgive me for the late reply, I have been very busy and unable to offer support recently. I intend to get back to actively developing this project sometime in the near future.

Anyways, getting to your question, the UI colour must in fact be the default orange or the program will not work.
