### ISSUE TITLE
Route complete -> Abort

### ISSUE THREAD

**Issue by Eismoritz** [skai2/EDAutopilot#9]
Whenever I set a route it says Route Complete and then Aborting.
Then, my ship is slowed down to 0% and nothing happens.
What did I do wrong?

**Comment by skai2** [comment]
Hey there friend,

Did you modify the colour of your UI?
The program will only work with the default UI colour
And at least 720p resolution.

Cheers!



From: Eismoritz
Sent: Saturday 1 December, 12:31
Subject: [skai2/EDAutopilot] Route complete -> Abort (#9)
To: skai2/EDAutopilot
Cc: Subscribed


Whenever I set a route it says Route Complete and then Aborting.
Then, my ship is slowed down to 0% and nothing happens.
What did I do wrong?

**Comment by Eismoritz** [comment]
Nope, I had a different UI recently, but changed back to default. My resolution is 720p

**Comment by Eismoritz** [comment]
Well, I managed to solve it by delete and reinstall the GetNavPointOffset folder.

**Comment by Eismoritz** [comment]
I managed to solve this problem by reinstall the GetNavPointOffset folder.
Right now I got the problem that whenever i set a route it says "Aligning ship" and it only uses the pitch up key and the roll right key.
